"""initial schema

Revision ID: 009e9c12ac00
Revises: 
Create Date: 2026-03-13 10:23:09.853599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '009e9c12ac00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_products',
    sa.Column('code', sa.Enum('VIDEO_UP_TO_2H', 'VIDEO_UP_TO_4H', name='product_type_enum'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_video_duration_sec', sa.Integer(), nullable=False),
    sa.Column('max_shorts_generated', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_video_duration_sec > 0', name='billing_products_max_video_duration_positive'),
    sa.CheckConstraint('price_amount > 0', name='billing_products_price_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CUSTOMER', name='user_role_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING_VERIFICATION', 'SUSPENDED', 'DELETED', name='user_status_enum'), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('token_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fingerprint_hash', sa.String(length=255), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('mercadopago_customer_id', sa.String(length=255), nullable=True),
    sa.Column('otp_hash', sa.String(length=128), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=False),
    sa.Column('otp_last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_challenge_id', sa.String(length=128), nullable=True),
    sa.Column('otp_challenge_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mercadopago_customer_id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index(op.f('ix_users_otp_challenge_id'), 'users', ['otp_challenge_id'], unique=False)
    op.create_index('ix_users_phone_status', 'users', ['phone_number', 'status'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=255), nullable=True),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_idempotency_keys_user_key', 'idempotency_keys', ['user_id', 'key'], unique=True)
    op.create_table('purchases',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('billing_provider', sa.Enum('STRIPE', 'MERCADOPAGO', 'MANUAL', name='billing_provider_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'CANCELED', 'EXPIRED', name='purchase_status_enum'), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('provider_checkout_url', sa.Text(), nullable=True),
    sa.Column('provider_raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_total > 0', name='purchases_amount_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['billing_products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_product_id'), 'purchases', ['product_id'], unique=False)
    op.create_index('ix_purchases_provider_ext_id', 'purchases', ['billing_provider', 'provider_payment_id'], unique=False)
    op.create_index(op.f('ix_purchases_user_id'), 'purchases', ['user_id'], unique=False)
    op.create_index('ix_purchases_user_status', 'purchases', ['user_id', 'status'], unique=False)
    op.create_table('clip_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'QUEUED', 'PREPARING', 'AWAITING_MANUAL_LLM', 'FINALIZING', 'COMPLETED', 'FAILED', 'CANCELED', name='job_status_enum'), nullable=False),
    sa.Column('input_mode', sa.Enum('MANUAL_PROMPT', 'DIRECT_AGENT', name='job_input_mode_enum'), nullable=False),
    sa.Column('source_type', sa.Enum('YOUTUBE_URL', 'DIRECT_UPLOAD', name='job_source_type_enum'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_storage_key', sa.String(length=500), nullable=True),
    sa.Column('video_title', sa.String(length=500), nullable=True),
    sa.Column('video_duration_sec', sa.Integer(), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=64), nullable=False),
    sa.Column('worker_job_id', sa.String(length=255), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_mode', sa.String(length=64), nullable=False),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('requested_shorts_count', sa.Integer(), nullable=False),
    sa.Column('merge_enabled', sa.Boolean(), nullable=False),
    sa.Column('transcript_storage_key', sa.String(length=500), nullable=True),
    sa.Column('prompt_storage_key', sa.String(length=500), nullable=True),
    sa.Column('ai_response_storage_key', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('video_duration_sec >= 0', name='clip_jobs_video_duration_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['billing_products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clip_jobs_product_id'), 'clip_jobs', ['product_id'], unique=False)
    op.create_index(op.f('ix_clip_jobs_purchase_id'), 'clip_jobs', ['purchase_id'], unique=False)
    op.create_index('ix_clip_jobs_purchase_status', 'clip_jobs', ['purchase_id', 'status'], unique=False)
    op.create_index(op.f('ix_clip_jobs_user_id'), 'clip_jobs', ['user_id'], unique=False)
    op.create_index('ix_clip_jobs_user_status', 'clip_jobs', ['user_id', 'status'], unique=False)
    op.create_table('clip_assets',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('SHORT_CLIP', 'MERGED_CLIP', 'THUMBNAIL', 'TRANSCRIPT', 'PROMPT', 'AI_RESPONSE', name='clip_asset_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('READY', 'PROCESSING', 'FAILED', 'DELETED', name='asset_status_enum'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_sec', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('end_sec', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_sec', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('merge_group', sa.String(length=120), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('thumbnail_text', sa.String(length=255), nullable=True),
    sa.Column('hashtags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_sec >= 0', name='clip_assets_end_non_negative'),
    sa.CheckConstraint('end_sec >= start_sec', name='clip_assets_end_after_start'),
    sa.CheckConstraint('start_sec >= 0', name='clip_assets_start_non_negative'),
    sa.ForeignKeyConstraint(['job_id'], ['clip_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clip_assets_job', 'clip_assets', ['job_id'], unique=False)
    op.create_index(op.f('ix_clip_assets_job_id'), 'clip_assets', ['job_id'], unique=False)
    op.create_index('ix_clip_assets_job_type', 'clip_assets', ['job_id', 'asset_type'], unique=False)
    op.create_table('job_events',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('JOB_CREATED', 'DOWNLOAD_STARTED', 'DOWNLOAD_FINISHED', 'TRANSCRIPTION_STARTED', 'TRANSCRIPTION_FINISHED', 'LLM_REQUEST_STARTED', 'LLM_REQUEST_FINISHED', 'CUT_GENERATED', 'RENDER_STARTED', 'RENDER_FINISHED', 'JOB_COMPLETED', 'JOB_FAILED', name='job_event_type_enum'), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['clip_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_events_job_created', 'job_events', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_index('ix_job_events_type', 'job_events', ['event_type'], unique=False)
    op.create_table('job_leases',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['clip_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('ix_job_leases_job', 'job_leases', ['job_id'], unique=False)
    op.create_table('job_queue',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'QUEUED', 'PREPARING', 'AWAITING_MANUAL_LLM', 'FINALIZING', 'COMPLETED', 'FAILED', 'CANCELED', name='job_queue_status_enum'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['clip_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('ix_job_queue_status', 'job_queue', ['status'], unique=False)
    op.create_index('ix_job_queue_worker', 'job_queue', ['worker_id'], unique=False)
    op.create_table('usage_metrics',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.Enum('GPU_SECONDS', 'CPU_SECONDS', 'STORAGE_BYTES', 'LLM_TOKENS', 'TRANSCRIPTION_SECONDS', name='usage_metric_type_enum'), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['clip_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_metrics_job', 'usage_metrics', ['job_id'], unique=False)
    op.create_index('ix_usage_metrics_type', 'usage_metrics', ['metric_type'], unique=False)
    op.create_index('ix_usage_metrics_user', 'usage_metrics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_metrics_user', table_name='usage_metrics')
    op.drop_index('ix_usage_metrics_type', table_name='usage_metrics')
    op.drop_index('ix_usage_metrics_job', table_name='usage_metrics')
    op.drop_table('usage_metrics')
    op.drop_index('ix_job_queue_worker', table_name='job_queue')
    op.drop_index('ix_job_queue_status', table_name='job_queue')
    op.drop_table('job_queue')
    op.drop_index('ix_job_leases_job', table_name='job_leases')
    op.drop_table('job_leases')
    op.drop_index('ix_job_events_type', table_name='job_events')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_index('ix_job_events_job_created', table_name='job_events')
    op.drop_table('job_events')
    op.drop_index('ix_clip_assets_job_type', table_name='clip_assets')
    op.drop_index(op.f('ix_clip_assets_job_id'), table_name='clip_assets')
    op.drop_index('ix_clip_assets_job', table_name='clip_assets')
    op.drop_table('clip_assets')
    op.drop_index('ix_clip_jobs_user_status', table_name='clip_jobs')
    op.drop_index(op.f('ix_clip_jobs_user_id'), table_name='clip_jobs')
    op.drop_index('ix_clip_jobs_purchase_status', table_name='clip_jobs')
    op.drop_index(op.f('ix_clip_jobs_purchase_id'), table_name='clip_jobs')
    op.drop_index(op.f('ix_clip_jobs_product_id'), table_name='clip_jobs')
    op.drop_table('clip_jobs')
    op.drop_index('ix_purchases_user_status', table_name='purchases')
    op.drop_index(op.f('ix_purchases_user_id'), table_name='purchases')
    op.drop_index('ix_purchases_provider_ext_id', table_name='purchases')
    op.drop_index(op.f('ix_purchases_product_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index('ix_idempotency_keys_user_key', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_users_phone_status', table_name='users')
    op.drop_index(op.f('ix_users_otp_challenge_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('billing_products')
    # ### end Alembic commands ###
