"""The cut-production schema, from nothing.

This replaces sixteen migrations. They are gone rather than superseded because most of what
they built is gone too: the billing products, the purchases and the credit ledger, the
seed-URL scheduler, the script jobs, and two tables nothing ever read. A chain that keeps
creating tables no model maps is not history worth preserving — it is the debris this
refactor exists to remove, re-created on every fresh install.

Every table here is on the path a video takes: the operator, the pipelines they configure,
what those pipelines find, the runs that turn a find into cuts, what the cuts become on the
channel, and what the channel says about them afterwards.

There is no upgrade path from the old chain, deliberately and with the owner's agreement: the
database is recreated.

Revision ID: 1db6dfbef733
Revises:
Create Date: 2026-09-15

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1db6dfbef733'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('schedule_hours_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cooldown_sec', sa.Integer(), nullable=False),
    sa.Column('max_daily_jobs', sa.Integer(), nullable=False),
    sa.Column('default_clip_mode', sa.String(length=64), nullable=False),
    sa.Column('default_video_ratio', sa.String(length=32), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('publish_targets',
    sa.Column('platform', sa.Enum('TELEGRAM', 'YOUTUBE', 'TIKTOK', 'INSTAGRAM', name='publish_platform_enum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_ref', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=True),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('connection_status', sa.Enum('DISCONNECTED', 'CONNECTED', 'RECONNECT_REQUIRED', name='publish_target_connection_status_enum'), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('granted_scopes', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=128), nullable=True),
    sa.Column('autopublish_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('autopublish_enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_publish_targets_channel', 'publish_targets', ['platform', 'channel_id'], unique=True, postgresql_where='channel_id IS NOT NULL')
    op.create_table('users',
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CUSTOMER', name='user_role_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING_VERIFICATION', 'SUSPENDED', 'DELETED', name='user_status_enum'), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('token_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fingerprint_hash', sa.String(length=255), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('mercadopago_customer_id', sa.String(length=255), nullable=True),
    sa.Column('otp_hash', sa.String(length=128), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=False),
    sa.Column('otp_last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_challenge_id', sa.String(length=128), nullable=True),
    sa.Column('otp_challenge_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mercadopago_customer_id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index(op.f('ix_users_otp_challenge_id'), 'users', ['otp_challenge_id'], unique=False)
    op.create_index('ix_users_phone_status', 'users', ['phone_number', 'status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_actor_created', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_ip_created', 'audit_logs', ['ip_address', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_target_created', 'audit_logs', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_table('automation_states',
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('last_automation_run_id', sa.String(length=64), nullable=True),
    sa.Column('running_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('running_run_id', sa.String(length=64), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('source_cooldowns_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automation_states_next_due', 'automation_states', ['next_due_at'], unique=False)
    op.create_index(op.f('ix_automation_states_pipeline_id'), 'automation_states', ['pipeline_id'], unique=True)
    op.create_table('clip_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'QUEUED', 'PREPARING', 'AWAITING_MANUAL_LLM', 'FINALIZING', 'COMPLETED', 'FAILED', 'CANCELED', name='job_status_enum'), nullable=False),
    sa.Column('input_mode', sa.Enum('MANUAL_PROMPT', 'DIRECT_AGENT', name='job_input_mode_enum'), nullable=False),
    sa.Column('source_type', sa.Enum('YOUTUBE_URL', 'DIRECT_UPLOAD', name='job_source_type_enum'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_storage_key', sa.String(length=500), nullable=True),
    sa.Column('video_title', sa.String(length=500), nullable=True),
    sa.Column('video_duration_sec', sa.Integer(), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=64), nullable=False),
    sa.Column('worker_job_id', sa.String(length=255), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_mode', sa.String(length=64), nullable=False),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('requested_shorts_count', sa.Integer(), nullable=False),
    sa.Column('merge_enabled', sa.Boolean(), nullable=False),
    sa.Column('transcript_storage_key', sa.String(length=500), nullable=True),
    sa.Column('transcript_with_speakers_storage_key', sa.String(length=500), nullable=True),
    sa.Column('speaker_turns_storage_key', sa.String(length=500), nullable=True),
    sa.Column('candidates_storage_key', sa.String(length=500), nullable=True),
    sa.Column('prompt_storage_key', sa.String(length=500), nullable=True),
    sa.Column('ai_response_storage_key', sa.String(length=500), nullable=True),
    sa.Column('qa_report_storage_key', sa.String(length=500), nullable=True),
    sa.Column('delivery_package_storage_key', sa.String(length=500), nullable=True),
    sa.Column('artifacts_manifest_storage_key', sa.String(length=500), nullable=True),
    sa.Column('runtime_status_storage_key', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('video_duration_sec >= 0', name='clip_jobs_video_duration_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clip_jobs_user_id'), 'clip_jobs', ['user_id'], unique=False)
    op.create_index('ix_clip_jobs_user_status', 'clip_jobs', ['user_id', 'status'], unique=False)
    op.create_table('discovery_sources',
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('YOUTUBE_TRENDING', 'YOUTUBE_SEARCH', 'NEWS', 'RSS', 'MANUAL', name='discovery_source_kind_enum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discovery_sources_pipeline', 'discovery_sources', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_discovery_sources_pipeline_id'), 'discovery_sources', ['pipeline_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=255), nullable=True),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_idempotency_keys_user_key', 'idempotency_keys', ['user_id', 'key'], unique=True)
    op.create_table('oauth_states',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redirect_uri', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_states_state'), 'oauth_states', ['state'], unique=True)
    op.create_table('clip_assets',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('SHORT_CLIP', 'MERGED_CLIP', 'THUMBNAIL', 'TRANSCRIPT', 'TRANSCRIPT_WITH_SPEAKERS', 'SPEAKER_TURNS', 'CANDIDATES', 'PROMPT', 'AI_RESPONSE', 'QA_REPORT', 'DELIVERY_PACKAGE', 'ARTIFACTS_MANIFEST', 'RUNTIME_STATUS', name='clip_asset_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('READY', 'PROCESSING', 'FAILED', 'DELETED', name='asset_status_enum'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_sec', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('end_sec', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_sec', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('merge_group', sa.String(length=120), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('thumbnail_text', sa.String(length=255), nullable=True),
    sa.Column('hashtags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_sec >= 0', name='clip_assets_end_non_negative'),
    sa.CheckConstraint('end_sec >= start_sec', name='clip_assets_end_after_start'),
    sa.CheckConstraint('start_sec >= 0', name='clip_assets_start_non_negative'),
    sa.ForeignKeyConstraint(['job_id'], ['clip_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clip_assets_job', 'clip_assets', ['job_id'], unique=False)
    op.create_index(op.f('ix_clip_assets_job_id'), 'clip_assets', ['job_id'], unique=False)
    op.create_index('ix_clip_assets_job_type', 'clip_assets', ['job_id', 'asset_type'], unique=False)
    op.create_table('job_events',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('JOB_CREATED', 'DOWNLOAD_STARTED', 'DOWNLOAD_FINISHED', 'TRANSCRIPTION_STARTED', 'TRANSCRIPTION_FINISHED', 'DIARIZATION_STARTED', 'DIARIZATION_FINISHED', 'LLM_REQUEST_STARTED', 'LLM_REQUEST_FINISHED', 'CUT_GENERATED', 'RENDER_STARTED', 'RENDER_FINISHED', 'QA_STARTED', 'QA_FINISHED', 'DELIVERY_PACKAGE_READY', 'JOB_COMPLETED', 'JOB_FAILED', name='job_event_type_enum'), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['clip_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_events_job_created', 'job_events', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_index('ix_job_events_type', 'job_events', ['event_type'], unique=False)
    op.create_table('job_leases',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['clip_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('ix_job_leases_job', 'job_leases', ['job_id'], unique=False)
    op.create_table('job_queue',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'QUEUED', 'PREPARING', 'AWAITING_MANUAL_LLM', 'FINALIZING', 'COMPLETED', 'FAILED', 'CANCELED', name='job_queue_status_enum'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['clip_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('ix_job_queue_status', 'job_queue', ['status'], unique=False)
    op.create_index('ix_job_queue_worker', 'job_queue', ['worker_id'], unique=False)
    op.create_table('video_candidates',
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('channel', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedup_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'RANKED', 'SELECTED', 'REJECTED', 'CONSUMED', name='video_candidate_status_enum'), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('trend_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('duplicate_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['discovery_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_candidates_pipeline_id'), 'video_candidates', ['pipeline_id'], unique=False)
    op.create_index('ix_video_candidates_pipeline_status', 'video_candidates', ['pipeline_id', 'status'], unique=False)
    op.create_index('ix_video_candidates_published_at', 'video_candidates', ['published_at'], unique=False)
    op.create_index('ix_video_candidates_source_status', 'video_candidates', ['source_id', 'status'], unique=False)
    op.create_index('uq_video_candidates_dedup_hash', 'video_candidates', ['dedup_hash'], unique=True, postgresql_where=sa.text('dedup_hash IS NOT NULL'))
    op.create_table('pipeline_jobs',
    sa.Column('pipeline_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_storage_key', sa.String(length=500), nullable=True),
    sa.Column('preset_id', sa.String(length=64), nullable=True),
    sa.Column('clip_mode', sa.String(length=64), nullable=False),
    sa.Column('video_ratio', sa.String(length=32), nullable=False),
    sa.Column('state', sa.Enum('DISCOVERED', 'SELECTED', 'QUEUED', 'DOWNLOADING', 'DOWNLOADED', 'TRANSCRIBING', 'TRANSCRIBED', 'ANALYZING', 'PROMPT_BUILDING', 'WAITING_AI', 'AI_COMPLETED', 'RENDERING', 'RENDERED', 'READY_TO_PUBLISH', 'REVIEW_REQUIRED', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'CANCELED', name='pipeline_state_enum'), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=64), nullable=False),
    sa.Column('worker_job_id', sa.String(length=255), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admission_key', sa.String(length=200), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['video_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_jobs_pending_enqueue', 'pipeline_jobs', ['enqueued_at'], unique=False, postgresql_where=sa.text('enqueued_at IS NULL'))
    op.create_index(op.f('ix_pipeline_jobs_pipeline_id'), 'pipeline_jobs', ['pipeline_id'], unique=False)
    op.create_index('ix_pipeline_jobs_pipeline_state', 'pipeline_jobs', ['pipeline_id', 'state'], unique=False)
    op.create_index('ix_pipeline_jobs_state', 'pipeline_jobs', ['state'], unique=False)
    op.create_index('uq_pipeline_jobs_admission_key', 'pipeline_jobs', ['admission_key'], unique=True, postgresql_where=sa.text('admission_key IS NOT NULL'))
    op.create_table('ai_executions',
    sa.Column('pipeline_job_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='ai_execution_status_enum'), nullable=False),
    sa.Column('prompt_chars', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_job_id'], ['pipeline_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_executions_job', 'ai_executions', ['pipeline_job_id'], unique=False)
    op.create_index(op.f('ix_ai_executions_pipeline_job_id'), 'ai_executions', ['pipeline_job_id'], unique=False)
    op.create_table('pipeline_events',
    sa.Column('pipeline_job_id', sa.UUID(), nullable=True),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.Enum('STATE_CHANGED', 'INFO', 'WARNING', 'ERROR', 'RETRY', 'HEARTBEAT', name='pipeline_event_type_enum'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_job_id'], ['pipeline_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_events_job_created', 'pipeline_events', ['pipeline_job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_events_pipeline_job_id'), 'pipeline_events', ['pipeline_job_id'], unique=False)
    op.create_index('ix_pipeline_events_service_created', 'pipeline_events', ['service', 'created_at'], unique=False)
    op.create_index('ix_pipeline_events_type', 'pipeline_events', ['event_type'], unique=False)
    op.create_table('publish_attempts',
    sa.Column('pipeline_job_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('initiator', sa.String(length=16), server_default='manual', nullable=False),
    sa.Column('budget_date', sa.Date(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=300), nullable=True),
    sa.Column('media_identity', sa.String(length=255), nullable=True),
    sa.Column('media_storage_key', sa.Text(), nullable=True),
    sa.Column('media_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCEEDED', 'FAILED_RETRYABLE', 'FAILED_FINAL', 'UNKNOWN', 'NEEDS_MANUAL_RESOLUTION', 'CANCELED', 'FAILED', name='publish_attempt_status_enum'), nullable=False),
    sa.Column('retryability', sa.Enum('RETRYABLE', 'NOT_RETRYABLE', 'REQUIRES_MANUAL_RESOLUTION', name='publish_retryability_enum'), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_id_source', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publisher_worker_id', sa.String(length=128), nullable=True),
    sa.Column('provider_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('upload_session_uri_encrypted', sa.Text(), nullable=True),
    sa.Column('bytes_uploaded', sa.BigInteger(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_job_id'], ['pipeline_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['publish_targets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_publish_attempts_budget', 'publish_attempts', ['budget_date', 'initiator'], unique=False)
    op.create_index('ix_publish_attempts_initiator_created', 'publish_attempts', ['initiator', 'created_at'], unique=False)
    op.create_index('ix_publish_attempts_job', 'publish_attempts', ['pipeline_job_id'], unique=False)
    op.create_index('ix_publish_attempts_pending_enqueue', 'publish_attempts', ['enqueued_at'], unique=False, postgresql_where=sa.text('enqueued_at IS NULL'))
    op.create_index(op.f('ix_publish_attempts_pipeline_job_id'), 'publish_attempts', ['pipeline_job_id'], unique=False)
    op.create_index(op.f('ix_publish_attempts_target_id'), 'publish_attempts', ['target_id'], unique=False)
    op.create_index('ix_publish_attempts_unresolved', 'publish_attempts', ['status'], unique=False, postgresql_where=sa.text("status IN ('UNKNOWN', 'NEEDS_MANUAL_RESOLUTION')"))
    op.create_index('uq_publish_attempts_idempotency', 'publish_attempts', ['idempotency_key'], unique=True)
    op.create_table('video_performance_snapshots',
    sa.Column('publish_attempt_id', sa.UUID(), nullable=False),
    sa.Column('publish_target_id', sa.UUID(), nullable=True),
    sa.Column('external_video_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capture_slot', sa.String(length=32), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.Column('availability', sa.String(length=32), nullable=False),
    sa.Column('privacy_status', sa.String(length=32), nullable=True),
    sa.Column('provider_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publish_attempt_id'], ['publish_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publish_target_id'], ['publish_targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publish_attempt_id', 'capture_slot', name='uq_video_performance_snapshot_slot')
    )
    op.create_index('ix_performance_snapshots_attempt_time', 'video_performance_snapshots', ['publish_attempt_id', 'captured_at'], unique=False)
    op.create_index('ix_performance_snapshots_captured', 'video_performance_snapshots', ['captured_at'], unique=False)
    op.create_index('ix_performance_snapshots_video', 'video_performance_snapshots', ['external_video_id'], unique=False)
    op.create_index(op.f('ix_video_performance_snapshots_publish_attempt_id'), 'video_performance_snapshots', ['publish_attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_performance_snapshots_publish_attempt_id'), table_name='video_performance_snapshots')
    op.drop_index('ix_performance_snapshots_video', table_name='video_performance_snapshots')
    op.drop_index('ix_performance_snapshots_captured', table_name='video_performance_snapshots')
    op.drop_index('ix_performance_snapshots_attempt_time', table_name='video_performance_snapshots')
    op.drop_table('video_performance_snapshots')
    op.drop_index('uq_publish_attempts_idempotency', table_name='publish_attempts')
    op.drop_index('ix_publish_attempts_unresolved', table_name='publish_attempts', postgresql_where=sa.text("status IN ('UNKNOWN', 'NEEDS_MANUAL_RESOLUTION')"))
    op.drop_index(op.f('ix_publish_attempts_target_id'), table_name='publish_attempts')
    op.drop_index(op.f('ix_publish_attempts_pipeline_job_id'), table_name='publish_attempts')
    op.drop_index('ix_publish_attempts_pending_enqueue', table_name='publish_attempts', postgresql_where=sa.text('enqueued_at IS NULL'))
    op.drop_index('ix_publish_attempts_job', table_name='publish_attempts')
    op.drop_index('ix_publish_attempts_initiator_created', table_name='publish_attempts')
    op.drop_index('ix_publish_attempts_budget', table_name='publish_attempts')
    op.drop_table('publish_attempts')
    op.drop_index('ix_pipeline_events_type', table_name='pipeline_events')
    op.drop_index('ix_pipeline_events_service_created', table_name='pipeline_events')
    op.drop_index(op.f('ix_pipeline_events_pipeline_job_id'), table_name='pipeline_events')
    op.drop_index('ix_pipeline_events_job_created', table_name='pipeline_events')
    op.drop_table('pipeline_events')
    op.drop_index(op.f('ix_ai_executions_pipeline_job_id'), table_name='ai_executions')
    op.drop_index('ix_ai_executions_job', table_name='ai_executions')
    op.drop_table('ai_executions')
    op.drop_index('uq_pipeline_jobs_admission_key', table_name='pipeline_jobs', postgresql_where=sa.text('admission_key IS NOT NULL'))
    op.drop_index('ix_pipeline_jobs_state', table_name='pipeline_jobs')
    op.drop_index('ix_pipeline_jobs_pipeline_state', table_name='pipeline_jobs')
    op.drop_index(op.f('ix_pipeline_jobs_pipeline_id'), table_name='pipeline_jobs')
    op.drop_index('ix_pipeline_jobs_pending_enqueue', table_name='pipeline_jobs', postgresql_where=sa.text('enqueued_at IS NULL'))
    op.drop_table('pipeline_jobs')
    op.drop_index('uq_video_candidates_dedup_hash', table_name='video_candidates', postgresql_where=sa.text('dedup_hash IS NOT NULL'))
    op.drop_index('ix_video_candidates_source_status', table_name='video_candidates')
    op.drop_index('ix_video_candidates_published_at', table_name='video_candidates')
    op.drop_index('ix_video_candidates_pipeline_status', table_name='video_candidates')
    op.drop_index(op.f('ix_video_candidates_pipeline_id'), table_name='video_candidates')
    op.drop_table('video_candidates')
    op.drop_index('ix_job_queue_worker', table_name='job_queue')
    op.drop_index('ix_job_queue_status', table_name='job_queue')
    op.drop_table('job_queue')
    op.drop_index('ix_job_leases_job', table_name='job_leases')
    op.drop_table('job_leases')
    op.drop_index('ix_job_events_type', table_name='job_events')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_index('ix_job_events_job_created', table_name='job_events')
    op.drop_table('job_events')
    op.drop_index('ix_clip_assets_job_type', table_name='clip_assets')
    op.drop_index(op.f('ix_clip_assets_job_id'), table_name='clip_assets')
    op.drop_index('ix_clip_assets_job', table_name='clip_assets')
    op.drop_table('clip_assets')
    op.drop_index(op.f('ix_oauth_states_state'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index('ix_idempotency_keys_user_key', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_discovery_sources_pipeline_id'), table_name='discovery_sources')
    op.drop_index('ix_discovery_sources_pipeline', table_name='discovery_sources')
    op.drop_table('discovery_sources')
    op.drop_index('ix_clip_jobs_user_status', table_name='clip_jobs')
    op.drop_index(op.f('ix_clip_jobs_user_id'), table_name='clip_jobs')
    op.drop_table('clip_jobs')
    op.drop_index(op.f('ix_automation_states_pipeline_id'), table_name='automation_states')
    op.drop_index('ix_automation_states_next_due', table_name='automation_states')
    op.drop_table('automation_states')
    op.drop_index('ix_audit_logs_target_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_ip_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_phone_status', table_name='users')
    op.drop_index(op.f('ix_users_otp_challenge_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('uq_publish_targets_channel', table_name='publish_targets', postgresql_where='channel_id IS NOT NULL')
    op.drop_table('publish_targets')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
